version: '3'
services:


  mongo:
    image: mongo
    restart: always
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
        - /data:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example
    links:
      - mongo


  nodeWebSrv:
    build: .
    container_name: nodeWebSrv
    image: node/custom
    #command: "npm run start"
    environment:
      - NPM_CONFIG_LOGLEVEL=info
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    links:
      - mongo
